project:
  type: website
  output-dir: docs

website:
  title: "STA 9750"
  description:
    Basic Software Tools for Data Analysis
  site-url: "https://michael-weylandt.com/STA9750/"
  navbar:
    background: primary
    search: false
    right:
      - text: "Syllabus"
        href: "./syllabus.html"
      - text: "Pre-Assignments"
        href: "./preassignments.html"
      - text: "Labs"
        href: "./labs.html"
      - text: "Mini Projects"
        href: "./miniprojects.html"
      - text: "Course Project"
        href: "./project.html"
      - text: "Additional Resources"
        href: "./resources.html"
      - text: "Learning Objectives"
        href: "./objectives.html"

format:
  html:
    theme: sandstone
    margin-left: 0em
    toc: true
    code-copy: true
    toc_depth: 5
